-- AlterTable
ALTER TABLE "Card" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "List" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Workspace" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
